name: "Mise à jour de l'infra"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  static-analysis-checkov:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Analyse checkov
        run: docker run --rm -v "$PWD:/repo" bridgecrew/checkov:2 -d /repo --quiet

  static-analysis-tflint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Analyse TFLint
        run: docker run --rm -v "$PWD:/repo" -w /repo ghcr.io/terraform-linters/tflint:latest --recursive

  static-analysis-hadolint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Analyse Hadolint
        # Suppression de continue-on-error et no-fail pour rendre le job bloquant
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
          recursive: true

  terraform:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [ static-analysis-checkov, static-analysis-tflint, static-analysis-hadolint ]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: setup du secret terraform tfvars (evite d'avoir trop de variables)
        run: |
          umask 077
          cat > terraform/ci.auto.tfvars <<'EOF'
          ${{ secrets.TERRAFORM_TFVARS }}
          EOF

      # un plan, pas encore de apply ou quoi, ce serait plus complexe et sera géré après, avec backend distant et étude d'autres outils
      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan -no-color
      # dans tous les cas même après ça fonctionnera par un principe de PR, jamais de apply

  ansible:
    if: ${{ github.event_name == 'push' }}
    needs: [ static-analysis-checkov, static-analysis-tflint, static-analysis-hadolint ]
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        service: [ "caddy" ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH (pour Ansible)
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_KEY }}
          log-public-key: false

      - name: Désactiver HostKeyChecking
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Setup Ansible
        run: |
          pipx install ansible-core || echo "Ansible déjà installé"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install Ansible Collections(on a du docker compose community)
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ansible-galaxy collection install -r ansible/requirements.yml

      #https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations
      # avec la matrix tous les services définis vont faire N déplooiements ansible
      - name: "Déploiement de ${{ matrix.service }}"
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ansible/inventories/inventory.yml ansible/playbooks/deploy-${{ matrix.service }}.yml
