name: Appel d'un déploiement front (pour exemple)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  deploy:
    uses: jobacogiez-org/proxmox-gitops/.github/workflows/deploy-domains.yml@main
    secrets: 
      CADDY_SSH_KEY: ${{ secrets.CADDY_SSH_KEY }} 
